### ISSUE TITLE
navbar changes unexpectedly

### ISSUE THREAD

**Issue by twothicc** [Colon-WQ/Portfolio#107]
![alert_prompt](https://user-images.githubusercontent.com/61146198/123425066-3a31a280-d5f4-11eb-846b-4702f4970c32.png)

Not entirely sure how to replicate. Happens if you just naturally use the application

**Comment by twothicc** [comment]
Some changes appear to be unintended

![image](https://user-images.githubusercontent.com/61146198/123432165-a9ab9000-d5fc-11eb-9cf8-2e5c4f0e7cd5.png)
Navbar appears to be translucent.

![image](https://user-images.githubusercontent.com/61146198/123432243-bfb95080-d5fc-11eb-971d-1140d14cdeac.png)
Unusually large icon in home page.

![image](https://user-images.githubusercontent.com/61146198/123432346-dfe90f80-d5fc-11eb-89ff-9ae55ca30de6.png)
add a portfolio button color is the exact same as background.

**Comment by twothicc** [comment]
Gap at the bottom of homepage. Not sure if intentional.

![image](https://user-images.githubusercontent.com/61146198/123432697-37877b00-d5fd-11eb-9be6-3296134e1bd1.png)

**Comment by Chang-CH** [comment]
Home page is work in progress
