### ISSUE TITLE
Suggestions for Editor UI improvements

### ISSUE THREAD

**Issue by twothicc** [Colon-WQ/Portfolio#129]
![image](https://user-images.githubusercontent.com/61146198/124076093-6166f480-da78-11eb-8c08-531faabe048b.png)

When templates become too short in height, editor buttons will overflow and overlap. Could do without background color and align buttons in one line instead.

**Comment by Chang-CH** [comment]
Aligning as a row is not a good idea either as mobile users are limited by width not height.

Possible solutions might be setting breakpoints, detecting mobile viewport, or having controls only appear on hover.

Will look into this.
