### ISSUE TITLE
Unintended ripple effects on the panel when clicking button

### ISSUE THREAD

**Issue by twothicc** [Colon-WQ/Portfolio#142]
Steps to replicate

1. Login as Guest
2. Create a portfolio
3. Click on save

Issue is not tied specifically to Guest. However testing as Guest is the easiest and chosen as the recommended steps to replicate.

**Comment by twothicc** [comment]
Fixed by changing mui theme.
This changes will disable all ripple effects on any mui buttons.

props: {
      MuiButtonBase: {
        disableRipple: true
      }
}

**Comment by twothicc** [comment]
Changes were made under /client/src/styles/styles.js lines 97 to 101 and lines 50 to 54

**Comment by Chang-CH** [comment]
> 
> 
> Fixed by changing mui theme.
> This changes will disable all ripple effects on any mui buttons.
> 
> props: {
> MuiButtonBase: {
> disableRipple: true
> }
> }

This does not fix the issue. will look into it

**Comment by Chang-CH** [comment]
Copied from pull request description:

issue was due to position: static style applied to Floating action buttons. Ripple effect has buggy interactions depending on the styling on the button, for example: [Chrome specific bug](https://codesandbox.io/s/jolly-architecture-h1u1b?file=/src/Demo.js)
