### ISSUE TITLE
invalid RawDraftContentState on opening entry editor

### ISSUE THREAD

**Issue by Chang-CH** [Colon-WQ/Portfolio#152]
### Steps to replicate

1. Open editor

### Error message
`

invariant
../ Portfolio / client / node_modules / fbjs / lib / invariant.js: 40
convertFromRawToDraftState
../ Portfolio / client / node_modules / draft - js / lib / convertFromRawToDraftState.js: 211
r / a.createEditorState
../ Portfolio / client / node_modules / react - draft - wysiwyg / dist / react - draft - wysiwyg.js: 7
r
../ Portfolio / client / node_modules / react - draft - wysiwyg / dist / react - draft - wysiwyg.js: 7
constructClassInstance
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 12709
updateClassComponent
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 17425
beginWork
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 19073
callCallback
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 3945
invokeGuardedCallbackDev
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 3994
invokeGuardedCallback
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 4056
beginWork$1
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 23964
performUnitOfWork
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22776
workLoopSync
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22707
renderRootSync
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22670
performSyncWorkOnRoot
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22293
flushSyncCallbackQueueImpl / <
  C: /Users / no_space / Desktop / Orbital production / Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 11327
unstable_runWithPriority
../ Portfolio / client / node_modules / scheduler / cjs / scheduler.development.js: 468
runWithPriority$1
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 11276
flushSyncCallbackQueueImpl
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 11322
flushSyncCallbackQueue
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 11309
discreteUpdates$1
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22420
discreteUpdates
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 3756
dispatchDiscreteEvent
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 5889
EventListener.handleEvent * addEventBubbleListener
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 6011
addTrappedEventListener
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 8411
listenToNativeEvent
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 8374
listenToAllSupportedEvents / <
  C: /Users / no_space / Desktop / Orbital production / Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 8326
listenToAllSupportedEvents
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 8324
preparePortalMount
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 10549
completeWork
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 19597
completeUnitOfWork
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22815
performUnitOfWork
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22787
workLoopSync
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22707
renderRootSync
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22670
performSyncWorkOnRoot
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22293
flushSyncCallbackQueueImpl / <
  C: /Users / no_space / Desktop / Orbital production / Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 11327
unstable_runWithPriority
../ Portfolio / client / node_modules / scheduler / cjs / scheduler.development.js: 468
runWithPriority$1
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 11276
flushSyncCallbackQueueImpl
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 11322
flushSyncCallbackQueue
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 11309
discreteUpdates$1
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 22420
discreteUpdates
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 3756
dispatchDiscreteEvent
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 5889
EventListener.handleEvent * addEventBubbleListener
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 6011
addTrappedEventListener
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 8411
listenToNativeEvent
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 8374
listenToAllSupportedEvents / <
  C: /Users / no_space / Desktop / Orbital production / Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 8326
listenToAllSupportedEvents
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 8324
createRootImpl
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 25887
ReactDOMBlockingRoot
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 25835
createLegacyRoot
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 25900
legacyCreateRootFromDOMContainer
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 25981
legacyRenderSubtreeIntoContainer
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 26007
render
../ Portfolio / client / node_modules / react - dom / cjs / react - dom.development.js: 26103
  ./ src / index.js / <
    C: /Users / no_space / Desktop / Orbital production / Portfolio / client / src / index.js: 32
      ./ src / index.js
http://localhost:3000/static/js/main.chunk.js:8958:30
__webpack_require__
../ Portfolio / client / webpack / bootstrap: 856
fn
../ Portfolio / client / webpack / bootstrap: 150
1
http://localhost:3000/static/js/main.chunk.js:11765:18
__webpack_require__
../ Portfolio / client / webpack / bootstrap: 856
checkDeferredModules
../ Portfolio / client / webpack / bootstrap: 45
webpackJsonpCallback
../ Portfolio / client / webpack / bootstrap: 32
  (anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:65`

**Comment by twothicc** [comment]
Issue was due to initial texts not being updated for the other templates and has been fixed.

However, it seems that there is no need for the level of freedom provided by RTEs for some of the templates.

As such, I have made changes to the texts field of the info object to have to include { label: "...", type: "..." } to differentiate between the types of text editors we will provide for the entry. 

Currently, the type can be either "simpleText" or "complexText". Will change to be more permanent like an export from a file once discussions are done.

EntryObject's text will now be changed to a Mixed type to account for string from simpleText editors and JSON object from complexText editors.
