### ISSUE TITLE
Visual changes in Text Editor takes too long to happen after actual edits to text

### ISSUE THREAD

**Issue by twothicc** [Colon-WQ/Portfolio#163]
- RTE and TextField have already been moved to child components with their own internal states. Changes to text within these text editors occur internally and are only propagated to the parent EntryEditor component via the handleChange function passed down as a prop before the text editor component itself is unmounted.
- Although handleChange function is called with the intended changes, visual changes is slow to follow.
- With the original handleChange function, I suspect that setState is taking an unusually long amount of time to perform the changes to the changed fields. Due to the asynchronous nature of setState, when there are multiple text editor components, each text editor component will make copies of the old state and change their individual texts. As such, only the last queued setState operation's changes will make it through, and only after a ridiculously long period of waiting.

**Comment by Chang-CH** [comment]
### Reason for problem

- componentWillUnmount was used, which fires only AFTER editor was closed, when the editor itself is already unmounted.
- entryEditor setStates back to portfolio, texteditor's onClose updates non-existent editor state.
See: [React docs](this.props.onClose(https://reactjs.org/docs/react-component.html#componentwillunmount)

### Fix
- As pushed: update happens onBlur to ensure texteditor must update entry editor before entry editor can close.
