### ISSUE TITLE
TypeError: fields.colors is undefined when creating new About entry

### ISSUE THREAD

**Issue by Chang-CH** [Colon-WQ/Portfolio#25]
When creating the minimalist style about entry a type error is thrown.

Error logs: 

  52 | <Typography 
  53 |     variant="h1"
  54 |     component="h2" 
> 55 |     style={{color: fields.colors.header, backgroundColor: fields.colours.header, fontFamily: `${fields.fonts.titleFont}, Arial, Helvetica, sans-serif`}}
     | ^  56 | >
  57 |     About Me
  58 | </Typography>

**Comment by twothicc** [comment]
Fixed by changing colors to colours.
