### ISSUE TITLE
Issue with deleting pages

### ISSUE THREAD

**Issue by twothicc** [Colon-WQ/Portfolio#71]
### Delete Pages doesn't cause any changes to pages field in state.

![image](https://user-images.githubusercontent.com/61146198/122213330-6efa7700-cedb-11eb-8dc3-098fdbf4be34.png)
Attempt to delete directory boi.

![image](https://user-images.githubusercontent.com/61146198/122213507-9ea97f00-cedb-11eb-9a72-e3f20b5d6880.png)
When saving, state pages still contains boi page under directories.

**Comment by Chang-CH** [comment]
Bug fixes pushed
