### ISSUE TITLE
Problems saving new redline template

### ISSUE THREAD

**Issue by twothicc** [Colon-WQ/Portfolio#87]
### Intention to save this template
![image](https://user-images.githubusercontent.com/61146198/122730385-bbafca80-d2ac-11eb-8578-37776d5b3fa7.png)

### Encountered this issue
![image](https://user-images.githubusercontent.com/61146198/122730427-c8342300-d2ac-11eb-9d04-c2f9cc69581e.png)

Seems to be an issue with casting icon svg to string.

**Comment by Chang-CH** [comment]
Seems like the entire image object is being casted to string rather than saving it as an object.

See message in screenshot 2 -- svg was not present in any form in the screenshot. src was saved as a string representation of the react-icon
